### ISSUE TITLE
Fix "Complexity" issue in pyconfig/Deserializer/KeyValue.py

### ISSUE THREAD

**Issue by samdmarshall-danger** [samdmarshall/pyconfig#44]
Cyclomatic complexity is too high in function splitByConditions. (6)

https://codeclimate.com/github/samdmarshall/pyconfig/pyconfig/Deserializer/KeyValue.py#issue_578a47b4528e83000109236f

**Comment by samdmarshall** [comment]
This has been created as a result of mitigating #43. I have opened a support ticket with CodeClimate to see if there is a way to raise the cyclomatic complexity level that can be reached before raising a warning. I feel this code is fairly simple and doesn't need to be split up any farther.
