### ISSUE TITLE
SHA mismatch when installing via brew

### ISSUE THREAD

**Issue by stefanmunz** [samdmarshall/pyconfig#72]
**Type of issue**: Bug

We saw an several fresh machines an SHA mismatch when installing pyconfig via homebrew, see below.

---

**Related Output**: 

```
nb-xxx:~ xxx.yyy$ brew install samdmarshall/formulae/pyconfig
==> Installing pyconfig from samdmarshall/formulae
==> Downloading https://github.com/samdmarshall/pyconfig/archive/v1.1.3.tar.gz
==> Downloading from https://codeload.github.com/samdmarshall/pyconfig/tar.gz/v1.1.3
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: b7d5e7f0e6579d627dba330e5e8f24815be7a3e215c26220a343f9d7531ccf4b
Actual: 435548c305722e72cc4cd2d24c4e1940b97e9d0878936b733211e1100aa1146a
Archive: /Users/xxx.yyy/Library/Caches/Homebrew/pyconfig-1.1.3.tar.gz
To retry an incomplete download, remove the file above.
```
---

**Description**:

We could fix it temporarily by `brew edit samdmarshall/formulae/pyconfig` but that is not how it should be.

**Comment by samdmarshall** [comment]
wow, that is very weird; do you mind if i cut a new release instead to ensure nothing malicious is going on?

**Comment by stefanmunz** [comment]
Fine for me, just wanted to report it to you.

**Comment by samdmarshall** [comment]
ok, i've cut a new release and updated the formula and this seems to work now; going to close this issue for now. please re-open if you still have problems!
